comment_handle/urls.py
from django.conf.urls import include
from django.urls import path
from .views import HomePageView, CommentView


app_name = "home"

urlpatterns = [
    path('',HomePageView,name = "home"),
    path('comment', CommentView, name = "comment"),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comment_handle.urls')),
]

comment_handle/models.py
from django.db import models

# Create your models here.

class CommentModel(models.Model) :
    author = models.EmailField(max_length=120)
    comment = models.TextField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} comment'

comment_handle/forms.py
from django import forms
from comment_handle.models import CommentModel

class CommentForm(forms.ModelForm) :

    author = forms.CharField(label="", widget=forms.TextInput(
        attrs = {
                "id" : "author",
                'class' : 'form-control',
                }
    ))

    comment = forms.CharField(label="", widget=forms.Textarea(
    attrs = {
            "id" : "author-text",
            'class' : 'form-control',
            }
    ))

    class Meta :
        model = CommentModel
        fields = ("author", "comment")

comment_handle/views.py
from django.shortcuts import render,redirect
from .models import CommentModel
from .forms import CommentForm
# handle the post method off comment using def
def CommentView(request) :
    # simply just take the value from the form
    # check is the form valid, if yes then save the value to the model
    if request.method == 'POST' :
        form = CommentForm(request.POST)
        if form.is_valid() :
            instance = form.save()
            return redirect("home:home")
    
    return redirect("home:home")
    

def HomePageView(request) :
    # retriev all the comment to the homepage 
    comment = CommentModel.objects.all().order_by('date')
    return render(request, 'homepage.html', {
        'comment' : comment,
        'form' : CommentForm,
    })
        
            

comment_handle/templates/base.html
{% load staticfiles %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Anggardha</title>
    <link rel="shortcut icon" href= "{% static 'img/image.png' %}" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- import stuff,cdn and import css -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise" rel="stylesheet" type="text/css"/>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    
  </head>
  <body data-spy="scroll" data-target="#navbar-example2">
      <nav id="navbar-example2" class="navbar navbar-light fixed-top">
          <ul class="nav nav-pills" role="tablist" id="nav-list">
          <li class="nav-item">
              <a class="nav-link" href="#home">Home</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#experience">Experience</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#skills">Skills</a>
          </li>
          </ul>
        </nav>

    {% block body %}
      
    {% endblock body %}

    
    {% block js %}
      
    {% endblock js %}
      
    
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <form method="POST" class="comment" action="{% url 'home:comment' %}" onsubmit="return validateForm()">
            {% csrf_token %}  
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">What Do you think about my website?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <div class="modal-body">   
            <div class="form-group">
              <label for="recipient-name" class="col-form-label">Email:</label>
                  {{form.author}}
            </div>
            <div class="form-group">
              <label for="message-text" class="col-form-label">Comment:</label>
                  {{form.comment}}
            </div>    
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button class="btn btn-primary" onclick="comment()">Send Comment</button>
          </div>
          </div>
        </div>
        </form>
    </div>
    <nav class="navbar sticky-bottom navbar-light" id="footer">
        <div class="row" style="width:100%">
            <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <p class="text-center"><a class="item" href="https://id.linkedin.com/in/anggardha-febriano-369672128">
                    <i class='fab fa-linkedin-in' style="color:#ffbb33;font-size: 24px"></i>
                </a>
                <a class="item" href="https://github.com/anggardhanoano">
                    <i class='fab fa-github' style="color:#ffbb33;font-size: 24px"></i>
                </a>
                <a class="item" href="mailto:anggardhanoano@gmail.com?Subject=Hello">
                    <i class="fas fa-envelope" style="color:#ffbb33;font-size: 24px"></i>
                </a></p>
            </div>
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <p class="text-center" style="color:#ffbb33">Anggardha Febriano <i class="copyright icon"></i>2019</p>
      </div>
    </nav>

    <!-- floating button for comment modal -->
      <button type="button" class="btn btn-primary" id="comment" data-toggle="modal" data-target="#exampleModal">
          <i class="material-icons">comment</i>
        </button>
    
    <!-- js stuff -->
    <script src="{% static 'js/jquery.js'%}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
    <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
    <script>

        // function for smooth navbar hide when scroll
        var prevScrollpos = window.pageYOffset;
        window.onscroll = function() {
            var currentScrollPos = window.pageYOffset;
              if (prevScrollpos > currentScrollPos) {
                    document.getElementById("navbar-example2").style.top = "0";
              } else {
                  document.getElementById("navbar-example2").style.top = "-50px";
              }
              prevScrollpos = currentScrollPos;
          }

        // function for validate the comment form
        function validateForm() {
            check = $("#author").val().trim().toLowerCase();
            console.log(check)
            look = check.search("@")    
            if (check.length <= 8) {
              alert("Please enter valid email");
              return false
            }else if ( look == -1) {
              alert("Your Email Is Not Valid");
              return false;
            }
          }            
</script>
  </body>
</html>

comment_handle/templates/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}


{% block body %}
<!-- start modal for about -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title">About Me</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12" id="bio">
          <img src="{% static 'img/angga2.png' %}" id="myImage">
          </div>
          <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <div id="bio-text" style="margin-top:10px;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 
<!--end modal for about -->


<div data-spy="scroll" data-target="#navbar-example2" data-offset="0" id="content">  
  <!-- homepage stuff -->
    <div id="home" class="row">
      <div class="col">
      <h1 id="name" class="text-left">Hello, <br> my name is <span style="color:orange;font-weight: 800;">Anggardha</span></h1>
      <p id="desc">I'm a student in <span style="color:#ffdf0f;font-weight: 800;">Universitas Indonesia</span>
      Taking <span style="color:blue;font-weight: 800;">Computer</span> <span style="color:red;font-weight: 800;">Science</span> Degree</p>
      <br>
      </div>
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <h3 class="text-center" data-aos="zoom-in"><a class="btn btn-primary aniview"  data-toggle="modal" id="about" data-target="#modal" style="z-index:1000;">About Me</a></h3>
      </div>
    </div>
    <!-- homepage stuff -->

    <!-- education stuff in card box -->
    <div id="experience" class="row">
        <div class="container" style="margin-bottom:10px;">
        <div class="row">
          <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6" data-aos="flip-left">
          <div class="card">
          <div class="card-body">
            <h5 class="card-title">Education</h5>
              <ul class="list-group">
                <a class="list-group-item">
                <i class="material-icons" style="color:green">check</i>
                <div class="bmd-list-group-col">
                <p class="list-group-item-heading">SDI Al-Fauzien</p>
                <p class="list-group-item-text">2006-2012</p>
                </div>
                </a>
                  
                <a class="list-group-item">
                <i class="material-icons" style="color:green">check</i>
                <div class="bmd-list-group-col">
                <p class="list-group-item-heading">SMPN 3 Depok</p>
                <p class="list-group-item-text">2012-2015</p>
                </div>
                </a>
                  
                <a class="list-group-item">
                <i class="material-icons" style="color:green">check</i>
                <div class="bmd-list-group-col">
                <p class="list-group-item-heading">SMAN 1 Depok</p>
                <p class="list-group-item-text">2015-2018</p>
                </div>
                </a>

                <a class="list-group-item">
                <i class="material-icons" style="color:orange">watch_later</i>
                <div class="bmd-list-group-col">
                <p class="list-group-item-heading">Universitas Indonesia</p>
                <p class="list-group-item-text">2018</p>
                </div>
                </a>
              </ul>
          </div>
          </div>
          </div>
          <!-- education stuff in card box -->

          <!-- experience stuff in cardh box -->
          <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card" id="experience-box" data-aos="flip-right">
          <div class="card-body">
            <h5 class="card-title">Experience</h5>
            <ul class="list-group">
              <a class="list-group-item">
              <div class="bmd-list-group-col">
              <p class="list-group-item-heading">Staff BEM Fasilkom Biro Perkembangan Teknologi Informasi</p>
              <p class="list-group-item-text">2019</p>                            
              </div>
              <img src="{% static 'img/bem.png' %}" style="height:30px;position: absolute;left: 80%;top: 15px;" >
              </a>
                                      
              <a class="list-group-item">                    
              <div class="bmd-list-group-col">
              <p class="list-group-item-heading">Under Construction Page @ uneev.id</p>
              <p class="list-group-item-text">2018</p>
              </div>
              <img src="{% static 'img/U.png' %}" style="height:30px;position: absolute;left: 80%;top: 15px;" >
              </a>
                                      
              <a class="list-group-item">
              <div class="bmd-list-group-col">
              <p class="list-group-item-heading">Main website uneev.id</p>
              <p class="list-group-item-text">On Progress</p>
              </div>
              <img src="{% static 'img/U.png' %}" style="height:30px;position: absolute;left: 80%;top: 15px;" >
              </a>                                        
            </ul>
        </div>
        </div>
        </div>
      </div>
      </div>
  </div>        
    <!-- experience stuff in card box -->


  <!-- skills stuff in table box -->
  <div id="skills" class="row" data-aos="zoom-in-down">
    <div class="container col-sm-12 col-md-12 col-lg-12 col-xl-12" id="skil">
      <table class="table table-hover">
      <thead>
        <tr style="background-color:orange">
          <th scope="col">Strong</th>
          <th scope="col">Experienced</th>
          <th scope="col">Familiar</th>
        </tr>
      </thead>
      <tbody>        
      <tr>
        <td>Python</td>
        <td>Javascript</td>
        <td>React Js</td>
      </tr>
      <tr>
        <td>Django</td>
        <td>Java</td>
        <td>PHP</td>
      </tr>
      <tr>
        <td>Html</td>
        <td>MySQL</td>
        <td>PostgreSQL</td>
      </tr>
      <tr>
        <td>CSS</td>
        <td>SemanticUI CSS</td>
        <td></td>
      </tr>
      <tr>
        <td>Bootsrap CSS</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>Materialize CSS</td>
        <td></td>
        <td></td>
      </tr>  
      </tbody>
      </table>
    </div>
    </div>      
  </div>
  <!-- skills stuff in table box -->

  <!-- retrieve all comment in comment-list -->
  <div class="container" id="comment-list" data-aos="fade-up">
    <h1 class="text-center">Comment from my visitors</h1>
    <ul class="list-group">
      {% for c in comment %}
      <li class="list-group-item">
      <div class="bmd-list-group-col">
        <p class="list-group-item-heading">{{c.author}}</p>
        <p class="list-group-item-text">{{c.comment}}</p>
        <p class="list-group-item-text">{{c.date | timesince}} ago</p>
      </div>
      </li>
      {% empty %}
      <h4 class="text-center">No one has commented on this web yet</h4>
      {% endfor %}            
    </ul>
  </div>
  </div>
{% endblock body %}
    



{% block js %}
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script language="JavaScript" type="text/javascript">

    // initialise AOS js
    AOS.init(); 


    var aText = new Array(
        "Hello,my name is Anggardha Febriano, people usually call me Angga or Anggardha. I was born 25 February 2000 in Jogjakarta.I'm an optimistic person with a big dreams that i want to reach.I like sport very much, escpecially Futsal and Taekwondo. Thank You for Visiting my Website!"
    );
    var iSpeed = 100; // time delay of print out
    var iIndex = 0; // start printing array at this posision
    var iArrLength = aText[0].length; // the length of the text array
    var iScrollAt = 20; // start scrolling up at this many lines
    
    var iTextPos = 0; // initialise text position
    var sContents = ''; // initialise contents variable
    var iRow; // initialise current row
 
    function typewriter()
    {
      sContents =  ' ';
      iRow = Math.max(0, iIndex-iScrollAt);
      var destination = document.getElementById("bio-text");
      
      while ( iRow < iIndex ) {
        sContents += aText[iRow++] + '<br />';
      }
      destination.innerHTML = sContents + aText[iIndex].substring(0, iTextPos) + "_";
      if ( iTextPos++ == iArrLength ) {
        iTextPos = 0;
        iIndex++;
        if ( iIndex != aText.length ) {
        iArrLength = aText[iIndex].length;
        setTimeout("typewriter()", 500);
        }
      } else {
        setTimeout("typewriter()", iSpeed);
      }
    }
    typewriter();
</script>
{% endblock js %}
    